Master
galacticpolymath/gp-frontend pull request #10
Opened 2022-08-21 19:45 UTC by chengp3

2022-08-28 17:46 UTC, kenziebottoms requested changes
This is amazing!!!! Thank you!!!!

How do you feel about using `/lessons/1/en-us` instead of `/lessons/en-us/1`? I think that makes more sense structurally.

2022-08-28 17:46 UTC, kenziebottoms commented on pages/lessons/[loc]/[id].js
> +          <div style={{display: "flex", justifyContent: "space-between"}}>
```suggestion
          <div className="d-flex justify-content-between">
```

2022-08-28 17:48 UTC, kenziebottoms commented on pages/lessons/[loc]/[id].js
> +          <div style={{display: "flex", justifyContent: "space-between"}}>
we also need to redirect `/lessons/1` to the default translation

2022-08-29 14:38 UTC, chengp3 commented
Absolutely yes I agree but unfortunately the i18n module in react doesn’t
create urls in that form afaik?

On Sun, Aug 28, 2022 at 10:46 AM Kenzie Bottoms ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> This is amazing!!!! Thank you!!!!
>
> How do you feel about using /lessons/1/en-us instead of /lessons/en-us/1?
> I think that makes more sense structurally.
> ------------------------------
>
> In pages/lessons/[loc]/[id].js
> <https://github.com/galacticpolymath/gp-frontend/pull/10#discussion_r956760582>
> :
>
> > @@ -39,12 +40,15 @@ const LessonDetails = ({ lesson }) => {
>
>      <Layout>
>
>        <div className="bg-light-gray p-4">
>
>          <div className="container">
>
> -          {lastSubRelease && (
>
> -            <p>
>
> -              Version {lastSubRelease.version}{' '}
>
> -              (Updated {format(new Date(lastSubRelease.date), 'MMM d, yyyy')})
>
> -            </p>
>
> -          )}
>
> +          <div style={{display: "flex", justifyContent: "space-between"}}>
>
>
> ⬇️ Suggested change
>
> -          <div style={{display: "flex", justifyContent: "space-between"}}>
>
> +          <div className="d-flex justify-content-between">
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/galacticpolymath/gp-frontend/pull/10#pullrequestreview-1087892799>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFODO6C3O7TGPBJ2G2CF6OLV3OQWTANCNFSM57FOPDGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-09-05 18:57 UTC, kenziebottoms commented
> Absolutely yes I agree but unfortunately the i18n module in react doesn’t create urls in that form afaik?


What do you mean? It looks to me like you're creating the URLs in that format in `LocDropdown.js#22` and by changing that, and moving `pages/lessons/[loc]/[id].js` to `pages/lessons/[id]/[loc].js` i think we can swap params.

2023-02-01 22:21 UTC, closed without merging